version: "3"

services:
  client:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  api:
    image: ledharaujo/vanilla-api
    container_name: vanilla_api
    ports:
      - 3000:3000
    restart: always
